#!/usr/bin/perl 
=head1 NAME

  rstats client

=head1 USAGE

 rmstatc host [type] [params]

=head1 AUTHOR

 ~AsmodeuS~ (2007-2018) mailto:asm [at] abills.net.ua

=cut

use strict;
use warnings;

use IO::Socket;
my $rstats_port = 30003;
my $debug = 0;

if ($#ARGV<1) {
  print "rmstatc host [type] [params]\n";
  exit;
}

my $remote = IO::Socket::INET->new(
  Proto    => "tcp",
  PeerAddr => "$ARGV[0]",
  PeerPort => $rstats_port)
  or die "cannot connect to rmstats port at $ARGV[0]:$rstats_port $!\n";

$debug=1;
if ($debug) {
  print "== REQUEST ======================\n";
  print 'Host: '. $ARGV[0]  ."\n";
  print 'Command: '. $ARGV[1] ."\n";
  print 'Arguments: ' . join(' ', @ARGV[ 2..$#ARGV ]);
  print "\n";
  print "=================================\n";
}

#print "$ARGV[1] $ARGV[2]\n";
print $remote $ARGV[1].' ';
if($#ARGV > 1) {
  print $remote join(' ', @ARGV[2 .. $#ARGV]);
}
print $remote "\n";

while (<$remote>) {
  print;
};

1
