#!/usr/bin/perl 
=head1 NAME

  rstats client

=head1 USAGE

 rmstatc host [type] [params]

=head1 AUTHOR

 ~AsmodeuS~ (2007-2018) mailto:asm [at] abills.net.ua

=cut

use strict;
use warnings;

use IO::Socket;
my $rstats_port = 30003;

if ($#ARGV<1) {
  print "rmstatc host [type] [params]\n";
  exit;
}

my $remote = IO::Socket::INET->new(
  Proto    => "tcp",
  PeerAddr => "$ARGV[0]",
  PeerPort => $rstats_port)
  or die "cannot connect to rmstats port at $ARGV[0]:$rstats_port $!\n";

#print "$ARGV[1] $ARGV[2]\n";
print $remote "$ARGV[1] $ARGV[2]\n";

while (<$remote>) {
  print;
};

1
